//! Skill lock file for version management
//!
//! The skill.lock file tracks installation source and version information
//! for skills installed from remote sources (skillsmp.com, etc.)

use std::path::Path;

use serde::{Deserialize, Serialize};

use crate::error::{ServerError, ServerResult};

/// Skill lock file structure
///
/// This file is automatically generated when installing a skill from
/// a remote source and is used for:
/// - Version tracking
/// - Update management
/// - Source verification
#[derive(Debug, Clone, Serialize, Deserialize)]
pub struct SkillLockFile {
    /// Skill name
    pub name: String,
    /// Installed version (if available)
    pub version: Option<String>,
    /// Original source (e.g., "skillsmp:code-review")
    pub source: Option<String>,
    /// Installation timestamp (ISO 8601 format)
    pub installed_at: Option<String>,
    /// Checksum of the installed package (SHA256)
    pub checksum: Option<String>,
}

impl SkillLockFile {
    /// Create a new lock file
    pub fn new(name: String, source: String) -> Self {
        Self {
            name,
            version: None,
            source: Some(source),
            installed_at: Some(chrono::Utc::now().to_rfc3339()),
            checksum: None,
        }
    }

    /// Create a lock file with version
    pub fn with_version(mut self, version: String) -> Self {
        self.version = Some(version);
        self
    }

    /// Create a lock file with checksum
    #[allow(dead_code)]
    pub fn with_checksum(mut self, checksum: String) -> Self {
        self.checksum = Some(checksum);
        self
    }

    /// Load a lock file from disk
    pub async fn load(path: &Path) -> ServerResult<Self> {
        let content = tokio::fs::read_to_string(path)
            .await
            .map_err(|e| ServerError::Operation(format!("Failed to read skill.lock: {}", e)))?;

        serde_yaml::from_str(&content)
            .map_err(|e| ServerError::Operation(format!("Failed to parse skill.lock: {}", e)))
    }

    /// Save the lock file to disk
    pub async fn save(&self, path: &Path) -> ServerResult<()> {
        let content = format!(
            "# skill.lock - Auto-generated, do not edit manually\n# https://github.com/ApeCloud/aries\n\n{}",
            serde_yaml::to_string(self).map_err(|e| {
                ServerError::Operation(format!("Failed to serialize skill.lock: {}", e))
            })?
        );

        tokio::fs::write(path, content)
            .await
            .map_err(|e| ServerError::Operation(format!("Failed to write skill.lock: {}", e)))
    }
}

#[cfg(test)]
mod tests {
    use super::*;

    #[test]
    fn test_create_lock_file() {
        let lock = SkillLockFile::new(
            "code-review".to_string(),
            "skillsmp:code-review".to_string(),
        );

        assert_eq!(lock.name, "code-review");
        assert_eq!(lock.source, Some("skillsmp:code-review".to_string()));
        assert!(lock.installed_at.is_some());
    }

    #[test]
    fn test_lock_file_with_version() {
        let lock = SkillLockFile::new(
            "code-review".to_string(),
            "skillsmp:code-review@2.0.0".to_string(),
        )
        .with_version("2.0.0".to_string());

        assert_eq!(lock.version, Some("2.0.0".to_string()));
    }

    #[test]
    fn test_lock_file_serialization() {
        let lock = SkillLockFile::new("test-skill".to_string(), "skillsmp:test-skill".to_string())
            .with_version("1.0.0".to_string());

        let yaml = serde_yaml::to_string(&lock).unwrap();
        assert!(yaml.contains("name: test-skill"));
        assert!(yaml.contains("version: 1.0.0"));
        assert!(yaml.contains("source: skillsmp:test-skill"));
    }

    #[test]
    fn test_lock_file_deserialization() {
        let yaml = r#"
name: code-review
version: "2.1.0"
source: "skillsmp:code-review@2.1.0"
installed_at: "2024-01-15T10:30:00Z"
checksum: "sha256:abc123"
"#;

        let lock: SkillLockFile = serde_yaml::from_str(yaml).unwrap();
        assert_eq!(lock.name, "code-review");
        assert_eq!(lock.version, Some("2.1.0".to_string()));
        assert_eq!(lock.source, Some("skillsmp:code-review@2.1.0".to_string()));
        assert_eq!(lock.checksum, Some("sha256:abc123".to_string()));
    }
}
